name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 0 * * *'  # This cron expression schedules the job to run daily at 00:30 UTC

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add Maven to PATH
      shell: powershell
      run: |
        $mvn = "C:\ProgramData\chocolatey\lib\maven\apache-maven-3.9.11\bin"
        Add-Content -Path $env:GITHUB_ENV -Value "PATH=$mvn;$env:PATH"
    - name: Check Java and Maven versions
      shell: powershell
      run: |
        java -version
        mvn -version
    - name: Run tests
      shell: powershell
      run: mvn -X test

    - name: Upload Cucumber HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-html-report
        path: target/reports/


 
